### ISSUE TITLE
Removed from forum ?

### ISSUE THREAD

**Issue by boermansjo** [plysken/ply_essentialmode#1]
Hi, May I ask you why this was removed from the forum FiveM ?
I am also working on a version of essentialmode with async.
Maybe we can work on something new together.
(oh and if you are french, you can reply in french to me :) )

**Comment by EserSahiner** [comment]
i think removed by kanersps

**Comment by boermansjo** [comment]
Ok, then I will continu my foundation mode so that he can't remove it :)

**Comment by plysken** [comment]
Not removed by Kanersps but he complained to a moderator witch delete my post.
Et oui je suis français. La version d'essentialmode que j'ai porté en Async fonctionne superbement bien, tu peux la prendre si tu veux. Ici elle ne sera pas supprimée.

**Comment by boermansjo** [comment]
Ok. Merci pour l'information.
